scrapinghub/web-poet

- CHANGELOG.rst
- docs/advanced/additional_requests.rst
- docs/advanced/meta.rst
- docs/api_reference.rst
- docs/index.rst
- tests/test_page_inputs.py
- web_poet/__init__.py
- web_poet/page_inputs.py
**NOTES:** This is built on top of the https://github.com/scrapinghub/web-poet/pull/22 branch.
> Introduce Meta as a way to pass information inside a PO

- CHANGELOG.rst
- docs/conf.py
- docs/intro/from-ground-up.rst
- docs/intro/tutorial.rst
- docs/requirements.txt
- setup.py
- tests/conftest.py
- tests/test_mixins.py
- tests/test_page_inputs.py
- tests/test_pages.py
- tox.ini
- web_poet/__init__.py
- web_poet/mixins.py
- web_poet/page_inputs.py
- web_poet/pages.py
- web_poet/utils.py
This is https://github.com/scrapinghub/web-poet/pull/29 + https://github.com/scrapinghub/web-poet/pull/24, but sent against master branch, to ensure merging this doesn't depend on anything else.
TODO:
Out o scope for this PR:
* implement HttpResponse.urljoin (can be done later)
* implement HttpResponse.base_url (can be done later)
* further clean-up of mixing (can be done later)
* clean-up of WebPage class?
* implement BrowserHtml (though we should do it before the release, as it might change code significantly)
* implement HttpRequestHeaders (though we should do it before the release, as it might change code significantly)
> HttpResponse instead of ResponseData

- tests/test_page_inputs.py
- web_poet/page_inputs.py
From the recent enhancement in https://github.com/scrapinghub/web-poet/pull/30, it would seem that we'll need to support insantiating the `HttpResponseHeaders` from raw bytes values. In particular, frameworks like Scrapy uses header values in bytes format.
By default, https://github.com/aio-libs/multidict only supports strings and not bytes. Thus, an alternative constructor is proposed for ease of use.
> add from_bytes_dict alternative constructor for HttpResponseHeaders

- web_poet/overrides.py
Code which causes the warning (it's visible in web-poet testing suite):
```py
@handle_urls("example.com", overrides=POTopLevelOverriden1)
@handle_urls("example.com", overrides=POTopLevelOverriden1, exclude="/*.jpg|", priority=300)
class POTopLevel1(POBase):
expected_overrides = POTopLevelOverriden1
expected_patterns = Patterns(["example.com"], ["/*.jpg|"], priority=300)
expected_meta = {}  # type: ignore
```
Current warning message:
```
web_poet/overrides.py:157
/Users/kmike/svn/web-poet/web_poet/overrides.py:157: UserWarning: Multiple @handle_urls annotations with the same 'overrides' are ignored in the same Registry. Ignoring duplicate annotation on 'example.com' for <class 'tests.po_lib.POTopLevel1'>.
warnings.warn(
```
Warning message in this PR:
```
tests/po_lib/__init__.py:29 …
```
> Improve warning message for handle_urls

- tests/test_page_inputs.py
- web_poet/__init__.py
- web_poet/mixins.py
- web_poet/page_inputs/__init__.py
- web_poet/page_inputs/browser.py
- web_poet/page_inputs/http.py
In this PR url-less BrowserHtml is added. Unlike HttpResponseBody, its type is str, not bytes; this means selectors can be supported directly.
In autoextract-poet we had AutoextractHtml (https://github.com/scrapinghub/autoextract-poet/blob/aac08746c7ca9bc0baf07cfbf7773d616c26b1fb/autoextract_poet/page_inputs.py#L23), which is more similar to HttpResponse, as it contains URL.
I think we can add a similar class later, if needed. A design challenge would be to figure out wht should be a URL class - is the same as ResponseURL, or is it separate (BrowserURL) - assuming we're moving forward with https://github.com/scrapinghub/web-poet/pull/42.
> BrowserHtml

- docs/advanced/additional-requests.rst
- tests/test_requests.py
- web_poet/__init__.py
- web_poet/exceptions/core.py
- web_poet/page_inputs/client.py
- web_poet/requests.py
This is a backwards incompatible change. If we are to do it, we should do it as soon as possible.
When working on https://github.com/scrapinghub/web-poet/pull/50, I realized that HttpClient argument name is not consistent with the name of contextvar variable; argument name looks more clear.
There are also some minor changes / fixes to additional-requests docs, hope that's not an issue. I can make it a separate PR if needed.
> request_backend_var -> request_downloader_var

- docs/advanced/additional-requests.rst
- docs/advanced/retries.rst
- docs/index.rst
- web_poet/exceptions/core.py
I think this is the direction that we want to go.
I was worrying at first about how this could impact additional requests, but then I realized that page objects can handle retries of additional requests on their own when those do not require first retrying the original request, and when they do, they can raise `Retry` to trigger that. Retries trigger a new page object, so they cannot keep state for additional request retries across original request retries, but that should not be a big issue.
It does feel like examples like https://web-poet.readthedocs.io/en/stable/intro/tutorial.html#final-result are becoming increasingly misleading, and I am starting to wonder if we should start providing some non-Scrapy reference framework implementation that better illustrates what the simplest …
> New Retry exception

- web_poet/requests.py
There is an empty "Requests" section in the API docs; I wanted to remove it, but then realized request_downloader_var could be added to this section.
> include request_downloader_var in the generated API docs page

- docs/advanced/fields.rst
- tests/test_fields.py
- web_poet/fields.py
The code changes turn out to be trivial :) 
It might be possible to simplify the implementation, and don't use cached_method to implement `field` decorator, but I'm not sure it worth it.
For properties there might be a stronger cause for making them cached by default. I'm worried about code like this:
```py
if page.name:
item.product_name = page.name
```
Some features might be a bit harder to implement for properties later, e.g. exposing cache stats for cached properties or fields.
> Fields as properties

- .git-blame-ignore-revs
- pyproject.toml
- tests/conftest.py
- tests/po_lib/__init__.py
- tests/po_lib/nested_package/__init__.py
- tests/po_lib/nested_package/a_nested_module.py
- tests/test_fields.py
- tests/test_page_inputs.py
- tests/test_requests.py
- tests/test_utils.py
- web_poet/exceptions/http.py
- web_poet/fields.py
- web_poet/overrides.py
- web_poet/page_inputs/client.py
- web_poet/page_inputs/http.py
- web_poet/page_inputs/url.py
- web_poet/utils.py
Fixes https://github.com/scrapinghub/web-poet/issues/67.
I'm assuming @Gallaecio is not against it, based on https://github.com/scrapinghub/scrapy-poet/pull/68#discussion_r901532514 :)
> Use default black options

- docs/advanced/fields.rst
- tests/test_fields.py
- web_poet/fields.py
Motivation:
1. Allow custom extensions in third-party code, a point where additional information about a field can be stored
2. Introduce a structured FieldInfo, which can be used in other features
> allow to store meta information about Page Object fields

- docs/advanced/additional-requests.rst
- docs/advanced/page-params.rst
- docs/advanced/retries.rst
This is a minor discussion which stems from the discussion from https://github.com/scrapinghub/web-poet/pull/74/files#r953047078. 
I wanted to re-open the topic here again while the additional requests hasn't been picked up much steam yet. This would be a great opportunity to have our naming conventions more consistent.
----
In this PR, I'm leaning towards making it shorter since:
- It's easier to type 7 characters less
- `http.get()` and `http.post()` looks much better
----
TODO if this gets merged:
> rename "http_client" var to "http" in doc examples

- tests/po_lib/__init__.py
- tests/po_lib/a_module.py
- tests/po_lib/nested_package/__init__.py
- tests/po_lib/nested_package/a_nested_module.py
- tests/po_lib_sub/__init__.py
- tests/test_exceptions.py
- tests/test_fields.py
- tests/test_mixins.py
- tests/test_overrides.py
- tests/test_page_inputs.py
- tests/test_pages.py
- tests/test_requests.py
- tests/test_url.py
- tests/test_utils.py
- tests_extra/po_lib_sub_not_imported/__init__.py
- web_poet/overrides.py
- web_poet/page_inputs/client.py
Resolves https://github.com/scrapinghub/web-poet/issues/73
Not too bad as I thought it would be since my initial tests were breaking due to `.mypy_cache`. 😅
> ensure mypy validates tests

- tests/test_fields.py
Used as an example in https://github.com/zytedata/zyte-common-items/pull/15#issuecomment-1259094848
> add test for @field with other decorators

- docs/advanced/fields.rst
- tests/test_fields.py
- web_poet/fields.py
This adds support for an `out=` argument to `@field`, as proposed in https://github.com/zytedata/zyte-common-items/issues/18 (option 3). It only supports a list of callables, though it should be easy to also add support for a single callable. It only supports synchronous processors as async processors don't seem too useful and would change the signature of the field from sync to async which I find problematic.
I'm not sure how idiomatic (wrt both Python and web-poet) is the implementation but it's simple enough to be able to adjust it.
> Add support for field processors.

- docs/intro/overrides.rst
- docs/requirements.txt
- web_poet/rules.py
I've tried to simplify ApplyRule docstring, and also added an introduction for the Overrides (renamed to Apply Rules).
It seems overrides.rst might need a bit more cleanup (it became not very consistent after this PR, and it should be renamed to rules.rst), but I'd keep it out of scope for this PR.
> Documentation improvements for overrides (apply rules)

- tests_typing/test_fields.mypy-testing
* cover async fields
* cover `field()`, but without out processors
> more xfail typing tests for the "field" decorator

- README.rst
- docs/frameworks/additional-requests.rst
- docs/index.rst
- docs/intro/tutorial.rst
Changes:
- Reword the introductory paragraph on the README:
- Mention Python 3.7. It seems important to clarify early that this is Python-specific. By mentioning the minimum version here, we do not need to repeat that elsewhere either.
- Provide an upstream link on the first mention of the page object pattern.
- Merge the “Overview” section of the README into index.rst, and provide the documentation link from the README right after the introductory paragraph.
This minimizes the duplicate content from the user’s perspective. For users that read the README and then the documentation, duplicate information is now minimal.
- Use Sphinx’s `include` directive to include content from the README, to avoid duplicate content from a developer’s perspective.
- Removed mentions of the license from the …
> Shorten the README

- CHANGELOG.rst
- tests/po_lib/__init__.py
- tests/test_rules.py
- web_poet/rules.py
Resolves https://github.com/scrapinghub/web-poet/issues/86.
Related to the prior work in https://github.com/scrapinghub/web-poet/pull/96.
This unblocks the WIP in https://github.com/scrapinghub/scrapy-poet/pull/88 when considering use cases that needs multiple rules in a single PO.
It's not necessary to include this in the `0.6.0` release.
> update RulesRegistry to allow multiple rules in a single Page Object

- tests/test_fields.py
- web_poet/fields.py
I found that I needed this change to be able to [use a mixin for `ItemPage` subclasses that implements fields](https://github.com/zytedata/zyte-common-items/pull/19), since the mixin itself is not (*cannot be*, I think) an `ItemPage` subclass.
> FieldsMixin: ignore AttributeError from delattr

- .flake8
- setup.py
- tests/conftest.py
- tests/test_serialization.py
- tox.ini
- web_poet/serialization/__init__.py
- web_poet/serialization/api.py
- web_poet/serialization/functions.py
This is WIP but ready for review. It doesn't have docs yet and wasn't tested as a cache replacement in scrapy-poet.
The basic idea:
* This is mostly for serializing page objects and their attributes recursively. So it has some custom support for web-poet classes but otherwise Injectable attr-classes are serialized recursively.
* This means that unless a custom function is written (and it's written for `HttpResponse`), every attr-class is converted into a tree where leaves are primitive types. `HttpResponse`, on the other hand, is just two leaves: the body and a dict with all other fields (we wanted to save the body as a plain HTML file and to make sure we support custom serialization).
* The tree (a dict with dicts as nodes and `bytes` objects as leaves, typed as `SerializedData`) does …
> Serialization support

- tests/test_fields.py
Adding and fixing some use cases before **Approach 1** from https://github.com/scrapinghub/web-poet/issues/77 begins development.
> Add more test cases for subclasses using @field

- .pre-commit-config.yaml
Similar to scrapinghub/scrapy-poet@140239a which fixes the broken "linters" tox CI.
> bump black and isort versions

- tests/test_serialization.py
- web_poet/serialization/functions.py
It seems that without indenting "headers" field make HttpResponse-other.json quite unreadable in practice.
> Indent content of HttpResponse-other.json

- tests/test_rules.py
- web_poet/rules.py
I noticed it when running our testing suite. The warning before:
```
web_poet/rules.py:171
/Users/kmike/svn/web-poet/web_poet/rules.py:171: UserWarning: Similar URL patterns [Patterns(include=('example.com',), exclude=(), priority=500), Patterns(include=('example.com',), exclude=(), priority=500)] were declared earlier that use to_return=<class 'tests.po_lib_to_return.ProductSimilar'>. The first, highest-priority rule added to the registry will be used when matching against URLs. Consider updating the priority of these rules: [ApplyRule(for_patterns=Patterns(include=('example.com',), exclude=(), priority=500), use=<class 'tests.po_lib_to_return.SimilarProductPage'>, instead_of=<class 'tests.po_lib_to_return.ProductPage'>, to_return=<class 'tests.po_lib_to_return.ProductSimilar'>, …
```
> Improve the warning raised in case of duplicate rules

- web_poet/testing/fixture.py
savefixture command currently produces output like
>     "currencyRaw": "\u20ac",
instead of 
>     "currencyRaw": "€",
Is there a particular reason ensure_ascii is set to True?
> support non-ascii output in fixtures

- docs/page-objects/testing.rst
- tests/test_page_inputs.py
- tests/test_serialization.py
- tests/test_testing.py
- web_poet/exceptions/core.py
- web_poet/exceptions/http.py
- web_poet/page_inputs/client.py
- web_poet/page_inputs/http.py
- web_poet/serialization/functions.py
This adds two flags to HttpClient: one tells it to save all responses into an attribute, another one tells it to return saved responses if they are available and raise an exception if they are not. It also adds serialization support for HttpClient that saves/restores these responses and sets the second flag on the deserialized HttpClient. I don't currently see how can we set the first flag when we generate a test, maybe it shouldn't be a flag of `__init__` but some other check.
This requires having some fingerprinting code for HttpRequest (the one in this PR is a placeholder). Not sure how comprehensive should it be. The Scrapy one is quite complicated taking into account that URLs can have fragments, not all headers are important etc. The code in scrapy-poet that gets a fingerprint for …
> Add saving/loading of HttpClient responses

- docs/page-objects/testing.rst
- tests/test_testing.py
- web_poet/testing/__main__.py
- web_poet/testing/fixture.py
A command to print the current page object output, given the inputs stored in a fixture. It enables this very simplistic workflow: 
1. change a page object so that its output is correct (e.g. implement extraction for a field);
2. `python -m web_poet.testing rerun fixtures/pages.mywebsite.MyProductPage/test-1`;
3. copy relevant parts of the output, paste to the output.json file.
I think that even if we implement something which supports the TDD workflow better, a simple command to re-run the page object can still be useful.
TODO:
> python -m web_poet.testing rerun

- .github/workflows/tests-ubuntu.yml
- .github/workflows/tests-windows.yml
**Motivation**: A PR like #138 doesn't run its CI since it's not merging with master
> allow GitHub actions CI to run on PRs not merging with master

- web_poet/pages.py
The idea of the fix: apparently, `__init_subclass__` is called multiple times (once per base class?), but in the incorrect invocations class arguments are not passed. So, we just skip those - do nothing if a default is not set.
I prefer it to the name mangling because there can be multiple classes with the same `cls.__name__`, which means we'd need to switch to something like get_fq_class_name, which makes the implementation more complex.
Checked it using the following code:
```py
from web_poet import Injectable
import attrs
NOT_SET = object()
class BasePage(Injectable):
_skip_nonitem_fields = NOT_SET
def __init_subclass__(cls, skip_nonitem_fields = NOT_SET, **kwargs):        
super().__init_subclass__(**kwargs)
print(cls, kwargs)
if skip_nonitem_fields is not NOT_SET: …
```
> Another attrs.define fix

- .github/workflows/tests-ubuntu.yml
- .readthedocs.yml
Solves the issue of ReadTheDocs errors since it uses `async-lru==2.0.3` instead of `1.0.3` which is intended for Python 3.7 ([reference](https://readthedocs.org/projects/web-poet/builds/19661597/)).
The issue stems from not pinning the Python version in the `docs` toxenv which uses arbitrary Python version in ReadTheDocs.
This PR also adjusts GitHub actions as well.
> add .readthedocs.yml config

- .readthedocs.yml
From https://github.com/scrapinghub/web-poet/pull/148#issuecomment-1455611228
Default value is `False`. https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning
> turn off fail_on_warning

- docs/page-objects/fields.rst
- tests/conftest.py
- tests/test_pages.py
- web_poet/__init__.py
- web_poet/fields.py
- web_poet/mixins.py
- web_poet/pages.py
This extracts `ItemBase` from `ItemPage`, the only difference between them being `ItemPage` inheriting from `Injectable`. It also adds `ItemPartial` which too inherits from `ItemBase` but adds `FieldsMixin` instead of `Injectable`. Actually, as `Injectable` inherits from `FieldsMixin` we coud have just `ItemBase` (inheriting from `FieldsMixin`) and `ItemPage` and use `ItemBase` directly in the user code.
Both new classes can be renamed.
> Improve and document processors for nested items

- tests/test_requests.py
- tests/test_rules.py
- tests/test_testing.py
- web_poet/page_inputs/client.py
- web_poet/serialization/functions.py
This allows us to test requests that fail with HttpError, not just return a non-200 status.
> Store HttpError exceptions in HttpClient serialization

- .github/workflows/tests-ubuntu.yml
- .github/workflows/tests-windows.yml
- docs/api-reference.rst
- tests/conftest.py
- tests/test_mixins.py
- tox.ini
- web_poet/mixins.py
I opted in for a runtime check to simplify the implementation a bit. We can drop it after bumping min parsel version requirement.
> jmespath shortcut

- README.rst
- docs/api-reference.rst
- docs/conf.py
- docs/frameworks/index.rst
- docs/frameworks/rules.rst
- docs/index.rst
- docs/intro/from-ground-up.rst
- docs/intro/tutorial.rst
- docs/page-objects/index.rst
- docs/page-objects/items.rst
- docs/page-objects/rules.rst
- web_poet/rules.py
My goal was to greatly simplify https://web-poet.readthedocs.io/en/stable/page-objects/rules.html.
However, I wonder if I went too far; the new pages are ~25% of the old page in terms of line count.
I removed much of the content, and although I aimed to keep the core information around, I did not always do that. For example, the [entire last section](https://web-poet.readthedocs.io/en/stable/page-objects/rules.html#using-rules-from-external-packages) is gone without its information making it in any form into the new page; I wonder if we should keep some of that information.
I recommend reading the old page, then the new pages, and see how you feel about the missing information.
> Refactor the rules documentation

- docs/page-objects/inputs.rst
- tests/test_page_inputs.py
- web_poet/__init__.py
- web_poet/mixins.py
- web_poet/page_inputs/__init__.py
- web_poet/page_inputs/browser.py
- web_poet/page_inputs/http.py
Here BrowserResponse is added, similar to HttpResponse. The issue with BrowserHtml is that it doesn't allow to access the URL and status code of the response.
I haven't added headers for BrowserResponse for now; it seems we can add them later, as they'd be optional, like in HttpResponse.
> BrowserResponse dependency

- setup.py
[`Version.major` is added in 20.0.](https://packaging.pypa.io/en/latest/changelog.html#id17)
> Set the minimum packaging version.

- docs/api-reference.rst
- docs/page-objects/inputs.rst
- tests/test_page_inputs.py
- tests/test_rules.py
- web_poet/__init__.py
- web_poet/page_inputs/__init__.py
- web_poet/page_inputs/response.py
A way to address https://github.com/zytedata/zyte-spider-templates/issues/25.
Related PRs:
- https://github.com/scrapinghub/scrapy-poet/pull/184
- https://github.com/scrapy-plugins/scrapy-zyte-api/pull/161
- https://github.com/zytedata/zyte-spider-templates/pull/28
~Not quite sure if we should have a detailed documentation about this class in the tutorials since it may be deprecated in the next few months when Zyte API handles Auto-Configuration (_i.e. selecting the best extraction source between HttpResponse and BrowserResponse_).~ **EDIT:** Added docs.
> add new AnyResponse

- .coveragerc
- tests/test_page_inputs.py
- web_poet/mixins.py
- web_poet/page_inputs/http.py
`HttpRequest.from_form` is based on [Scrapy’s FormRequest.from_response()](https://github.com/scrapy/scrapy/blob/1282ddf8f77299edf613679c2ee0b606e96808ce/scrapy/http/request/form.py#L69), but with a minimal API and without support for the `click` thing which I don’t fully understand.
> Add base_url to Selector and implement HttpRequest.from_form

- tests/test_pages.py
- web_poet/pages.py
I am hoping the comment is out of date or wrong, but I am not 100% sure of what the line was meant to fix. @kmike Do you recall why this line was there? (it comes from the initial commit).
This change does break 2 scrapy-poet tests, but I believe those tests expectations are what’s wrong (https://github.com/scrapinghub/scrapy-poet/pull/218).
cc @kalessin
> Do not consider type(None) injectable

- tests/test_pages.py
- web_poet/pages.py
`isinstance(cls, type)` is True for `typing.GenericAlias` types, such as `list[...]` on Python 3.9 and 3.10 (see https://bugs.python.org/issue45665), but `issubclass()` produces "TypeError: issubclass() arg 1 must be a class" on such classes.
> Fix is_injectable() error with GenericAlias on Python < 3.11.

- .github/workflows/tests-ubuntu.yml
- .gitignore
- .readthedocs.yml
- pyproject.toml
- tests/po_lib/__init__.py
- tests/test_rules.py
- tox.ini
- web_poet/rules.py
Fix type checks for typed url-matcher, pin cssselect in the pinned env, switch to Python 3.13 for CI, pin package versions in the mypy check.
> Fix CI issues, bump CI Python versions.
