scrapinghub/web-poet

- .travis.yml
- docs/conf.py
- tox.ini
Add docs configuration to `tox.ini`
Run the configuration in travis.
Had to fix the static path that was breaking the build
> Feat tox docs

- tests/conftest.py
- tests/test_mixins.py
- tests/test_pages.py
- web_poet/mixins.py
Hey! I've added base_url and urljoin shortcuts in this PR. urljoin implementation is based on Scrapy's.
> base_url and urljoin shortcuts

- CHANGELOG.rst
- docs/conf.py
- docs/intro/from-ground-up.rst
- docs/intro/tutorial.rst
- docs/requirements.txt
- tests/test_mixins.py
- tests/test_page_inputs.py
- web_poet/page_inputs.py
Attempts to improve the docs and tests as noted down in the **TODO** section of https://github.com/scrapinghub/web-poet/pull/30.
> HttpResponse improvements

- web_poet/mixins.py
I think these FIXME comments no longer apply after https://github.com/scrapinghub/web-poet/pull/52, they're fixed by this PR.
> remove outdated FIXME comments

- docs/advanced/fields.rst
Some small doc updates in line with https://github.com/scrapinghub/web-poet/pull/53.
> small improvements to field docs

- docs/advanced/additional-requests.rst
- docs/advanced/retries.rst
- docs/intro/from-ground-up.rst
- docs/intro/tutorial.rst
Keeping it consistent with https://github.com/scrapinghub/scrapy-poet/pull/82
> update docs/docstrings to consistently use double-quotes

- setup.py
> declare web-poet as a package with type information

- pyproject.toml
- tox.ini
* move config to pyproject.toml
* add show_error_codes, to make it easier to write ignores
* bump mypy version
> improve mypy setup:

- tests/test_fields.py
- web_poet/fields.py
- web_poet/pages.py
Fixes GH-69.
~~I'm sending this PR against #62 because the same code is touched, and it seems #62 is close enough.~~
> Fixed fields in subclasses.

- CHANGELOG.rst
- docs/advanced/additional-requests.rst
- tests/test_page_inputs.py
- web_poet/page_inputs/http.py
Resolves https://github.com/scrapinghub/web-poet/issues/64.
Based from the https://github.com/scrapy/scrapy/issues/5601 Scrapy fix.
> ensure that the BOM is used to sniff the encoding first

- web_poet/rules.py
Missed out on https://github.com/scrapinghub/web-poet/pull/84
> remove incomplete parameter text in docs

- .flake8
Ignoring flake-bugbear warning, to fix the build.
> ignore B028

- .flake8
- docs/page-objects/testing.rst
- tests/test_testing.py
- web_poet/testing/fixture.py
- web_poet/testing/pytest.py
This fixes #131, following the approach outlined there.
> Fix GH-131

- CHANGELOG.rst
- tests/test_pages.py
- web_poet/pages.py
> fix `skip_nonitem_fields=True` doesn't work when the page object is an attrs class

- .readthedocs.yml
There is an error in readthedocs:
> Problem in your project's configuration. Invalid "build.os": expected one of (ubuntu-20.04, ubuntu-22.04), got ubuntu-22.10
> use supported Ubuntu version

- README.rst
> fix: build status badges

- tests/test_testing.py
Related to https://github.com/scrapinghub/scrapy-poet/pull/139
> Add a non-working test for to_item() exceptions

- tests/test_fields.py
- web_poet/fields.py
- web_poet/utils.py
> Support builtin types as field processors

- docs/page-objects/items.rst
> It may be worth explaining briefly why we are making this recommendation; it's not obvious, so people might think it's e.g. a stylistic choice to promote web-poet fields. — https://github.com/scrapinghub/web-poet/pull/165#discussion_r1163190244
> Justify recommending logic-free items

- CHANGELOG.rst
Let’s not disappoint @VMRuiz waiting for some other merge :smiley:
> Cover 0.15.0 in the changelog

- docs/page-objects/fields.rst
https://github.com/scrapinghub/web-poet/pull/153#issuecomment-1474504414
> Cover FieldsMixin

- setup.py
- tests/test_rules.py
- tox.ini
- web_poet/rules.py
Implemented because @proway2 is looking to implement something similar to the example code added to the docstring.
Any suggestions for a better name?
> Implement RulesRegistry.top_rules_for_item

- .pre-commit-config.yaml
- pyproject.toml
- tests/po_lib/__init__.py
- tests/test_page_inputs.py
- tests/test_pages.py
- tests/test_rules.py
- tox.ini
- web_poet/_base.py
- web_poet/annotated.py
- web_poet/fields.py
- web_poet/mixins.py
- web_poet/page_inputs/client.py
- web_poet/page_inputs/http.py
- web_poet/page_inputs/page_params.py
- web_poet/page_inputs/stats.py
- web_poet/pages.py
- web_poet/requests.py
- web_poet/rules.py
- web_poet/serialization/api.py
- web_poet/serialization/functions.py
- web_poet/serialization/utils.py
- web_poet/testing/fixture.py
- web_poet/testing/utils.py
- web_poet/utils.py
This is some old PR I had locally, I don't remember if the added type hints are for something specific like a mypy bump or are just random, but it's correct and in the current state it is a gradual improvement.
> Improve typing.
